## Handling the error within the function
```cpp
double  printDivision(int x, int y)
{
    if (y != 0)
        std::cout << static_cast<double>(x) / y;
    else
        std::cerr << "Error: Could not divide by zero\n";
    return x/y;
}

int main() {
    cout << printDivision(1,0);
    return 0;
}
```

## Passing errors back to the caller
```cpp
bool printDivision(int x, int y) {
    if (y == 0){
        std::cerr << "Error: could not divide by zero\n";
        return false;
    }

    std::cout << static_cast<double>(x) / y;
    return true;
}

int main(){
    cout << printDivision(1,0);
    return 0;
}
```

